ami_id            = "ami-0c9978668f8d55984"
instance_type     = "t2.micro"
availability_zone = "us-east-1a"
name              = "Prod_Instance"
env               = "Prod"
region            = "us-east-1"